### ISSUE TITLE
Фидбек по skillbox

### ISSUE THREAD

**Issue by mouzzli** [KlykovVasiliy/SkillboxJava#1]
На данный момент размышляю об приобретении курса от skillbox. Не могли бы вы дать фидбек по курсу в целом

**Comment by KlykovVasiliy** [comment]
Добрый день. Как по мне, так курс весьма интересный. На видео лекциях рассказывают материал. Далее делаешь домашнюю работу, если появляются трудности можешь по гуглить дополнительно материал в интернете, статьи, иногда на youtube ролики чтобы лучше разобраться. Сам SkillBox активно проводит интенсивы. Есть чат в котором находятся практически все студенты по направлению Java-разработчик и некоторые преподаватели. В этом чате могут как тебе помочь в чем-то, так и ты сам по желанию. Присутствует обратная связь с преподавателем. Домашние работы проверяются в среднем 1 день, бывает и больше. Но это уже если выпадает на выходной день у преподавателя или праздничные. По мимо основного курса со временем подключат дополнительные вспомогающие программы, так как: Универсальные навыки программиста, язык запросов SQL, Английский для IT-специалиста, Система контроля версий-Git. Приходится много информации брать из книг и статей в интернете, но я считаю что это только на пользу.
По этой скидке можешь получить дополнительную скидку https://live.skillbox.ru/invite/?hash=eyJwcm9tb2NvZGUiOiAiZmQwYWQ3YzItMjE5MC00ZmZiLTgyNWItY2FlODAxOTBmNzllIiwgImVtYWlsIjogImtseWtvdl92QG1haWwucnUifQ==
